import pyxel
from .parametres import COULEUR_POINT_J1, COULEUR_POINT_J2, RAYON_POINT, LARGEUR_BORD, LONGUEUR_BORD, ESPACE_ENTRE_POINTS

def afficher_scores(scorej1=0, scorej2=0):
    for i in range(scorej1):
        pyxel.circ(LONGUEUR_BORD + RAYON_POINT + i * (2 * RAYON_POINT + ESPACE_ENTRE_POINTS), (LARGEUR_BORD - 4 * RAYON_POINT - ESPACE_ENTRE_POINTS) / 2 + RAYON_POINT, RAYON_POINT, COULEUR_POINT_J1)

    for i in range(scorej2):
        pyxel.circ(LONGUEUR_BORD + RAYON_POINT + i * (2 * RAYON_POINT + ESPACE_ENTRE_POINTS), (LARGEUR_BORD - 4 * RAYON_POINT - ESPACE_ENTRE_POINTS) / 2 + ESPACE_ENTRE_POINTS + 3 * RAYON_POINT, RAYON_POINT, COULEUR_POINT_J2)
    

