TITRE = "foot !"

## terrain
LONGUEUR = 1000
LARGEUR = 600
LONGUEUR_BORD = 100  # et bord terrrain
LARGEUR_BORD = LONGUEUR_BORD *  LARGEUR / LONGUEUR

RAYON_CERLCE_CENTRE = 48
COULEUR_TERRAIN = 11
COULEUR_BORD = 13
COULEUR_MARQUAGES_SOL = 7
EPAISSEUR_MARQUAGES_SOL = 4
LONGUEUR_CAGES = 80  # 40 par default
LARGEUR_CAGES = 300  # 90 par default
RAYON_CORNER = 20
LONGUEUR_SURFACE_REPARATION = 107
LARGEUR_SURFACE_REPARATION = 213
DISTANCE_PT_PENALTY_CAGE = 73
RAYON_CERCLE_SURFACE_REPARATION = 53
RAYON_PT_PENALTY = 4
LONGUEUR_SURFACE_AVANT_CAGE = 37
LARGEUR_SURFACE_AVANT_CAGE = 97

# trait blanc de marquage inclu a chaque fois
LIMITE_OUEST_TERRAIN = LONGUEUR_BORD
LIMITE_EST_TERRAIN = LONGUEUR - LONGUEUR_BORD
LIMITE_NORD_TERRAIN = LARGEUR_BORD
LIMITE_SUD_TERRAIN = LARGEUR - LARGEUR_BORD
LIMITE_NORD_CAGE = LARGEUR / 2 - LARGEUR_CAGES / 2
LIMITE_SUD_CAGE = LARGEUR / 2 + LARGEUR_CAGES / 2
LIMITE_OUEST_CAGE_GAUCHE = LIMITE_OUEST_TERRAIN - LONGUEUR_CAGES + EPAISSEUR_MARQUAGES_SOL
LIMITE_EST_CAGE_DROITE = LIMITE_EST_TERRAIN + LONGUEUR_CAGES - EPAISSEUR_MARQUAGES_SOL
##

## balle
COEF_FROT_FLUIDE = 0.05
FROT_SEC = 1
RAYON_BALLE = 10
COULEUR_BALLE = 1
##

## joueur
RAYON_JOUEUR = 15
COULEUR_J1 = 3
COULEUR_J2 = 8
VITESSE_JOUEUR = 6
NB_EXECUTIONS_1_ACTION = 5  # le jeu tourne a 30 fps, ca fait 0.5 sec par action
##

## affichage score
RAYON_POINT = 7
COULEUR_POINT_J1 = COULEUR_J1
COULEUR_POINT_J2 = COULEUR_J2
ESPACE_ENTRE_POINTS = RAYON_POINT
##