import pyxel
from .parametres import *


def tracer_terrain():
        # couleur interieur terrain
        pyxel.rect(LONGUEUR_BORD, LARGEUR_BORD, LONGUEUR - 2 * LONGUEUR_BORD, LARGEUR - 2 * LARGEUR_BORD, COULEUR_TERRAIN)

        # corners
        pyxel.circ(LIMITE_OUEST_TERRAIN + EPAISSEUR_MARQUAGES_SOL / 2, LIMITE_NORD_TERRAIN + EPAISSEUR_MARQUAGES_SOL / 2, RAYON_CORNER, COULEUR_MARQUAGES_SOL)
        pyxel.circ(LIMITE_OUEST_TERRAIN + EPAISSEUR_MARQUAGES_SOL / 2, LIMITE_SUD_TERRAIN - EPAISSEUR_MARQUAGES_SOL / 2, RAYON_CORNER, COULEUR_MARQUAGES_SOL)
        pyxel.circ(LIMITE_EST_TERRAIN - EPAISSEUR_MARQUAGES_SOL / 2, LIMITE_NORD_TERRAIN + EPAISSEUR_MARQUAGES_SOL / 2, RAYON_CORNER, COULEUR_MARQUAGES_SOL)
        pyxel.circ(LIMITE_EST_TERRAIN - EPAISSEUR_MARQUAGES_SOL / 2, LIMITE_SUD_TERRAIN - EPAISSEUR_MARQUAGES_SOL / 2, RAYON_CORNER, COULEUR_MARQUAGES_SOL)

        pyxel.circ(LIMITE_OUEST_TERRAIN + EPAISSEUR_MARQUAGES_SOL / 2, LIMITE_NORD_TERRAIN + EPAISSEUR_MARQUAGES_SOL / 2, RAYON_CORNER - EPAISSEUR_MARQUAGES_SOL, COULEUR_TERRAIN)
        pyxel.circ(LIMITE_OUEST_TERRAIN + EPAISSEUR_MARQUAGES_SOL / 2, LIMITE_SUD_TERRAIN - EPAISSEUR_MARQUAGES_SOL / 2, RAYON_CORNER - EPAISSEUR_MARQUAGES_SOL, COULEUR_TERRAIN)
        pyxel.circ(LIMITE_EST_TERRAIN - EPAISSEUR_MARQUAGES_SOL / 2, LIMITE_NORD_TERRAIN + EPAISSEUR_MARQUAGES_SOL / 2, RAYON_CORNER - EPAISSEUR_MARQUAGES_SOL, COULEUR_TERRAIN)
        pyxel.circ(LIMITE_EST_TERRAIN - EPAISSEUR_MARQUAGES_SOL / 2, LIMITE_SUD_TERRAIN - EPAISSEUR_MARQUAGES_SOL / 2, RAYON_CORNER - EPAISSEUR_MARQUAGES_SOL, COULEUR_TERRAIN)

        pyxel.rect(0, 0, LONGUEUR, LARGEUR_BORD, COULEUR_BORD)
        pyxel.rect(0, 0, LONGUEUR_BORD, LARGEUR, COULEUR_BORD)
        pyxel.rect(LONGUEUR - LONGUEUR_BORD, 0, LONGUEUR_BORD, LARGEUR, COULEUR_BORD)
        pyxel.rect(0, LARGEUR - LARGEUR_BORD, LONGUEUR, LARGEUR_BORD, COULEUR_BORD)

        # cages
        pyxel.rect(LONGUEUR_BORD - LONGUEUR_CAGES + EPAISSEUR_MARQUAGES_SOL, LARGEUR / 2 - LARGEUR_CAGES / 2, LONGUEUR_CAGES, LARGEUR_CAGES, COULEUR_J2)
        pyxel.rect(LONGUEUR_BORD - LONGUEUR_CAGES + 2 * EPAISSEUR_MARQUAGES_SOL, LARGEUR / 2 - LARGEUR_CAGES / 2 + EPAISSEUR_MARQUAGES_SOL, LONGUEUR_CAGES - 2 * EPAISSEUR_MARQUAGES_SOL, LARGEUR_CAGES - 2 * EPAISSEUR_MARQUAGES_SOL, COULEUR_BORD)
        pyxel.rect(LONGUEUR - LONGUEUR_BORD - EPAISSEUR_MARQUAGES_SOL, LARGEUR / 2 - LARGEUR_CAGES / 2, LONGUEUR_CAGES, LARGEUR_CAGES, COULEUR_J1)
        pyxel.rect(LONGUEUR - LONGUEUR_BORD, LARGEUR / 2 - LARGEUR_CAGES / 2 + EPAISSEUR_MARQUAGES_SOL, LONGUEUR_CAGES - 2 * EPAISSEUR_MARQUAGES_SOL, LARGEUR_CAGES - 2 * EPAISSEUR_MARQUAGES_SOL, COULEUR_BORD)

        # cercles surface reparation
        pyxel.circ(LIMITE_OUEST_TERRAIN + DISTANCE_PT_PENALTY_CAGE, LARGEUR / 2, RAYON_CERCLE_SURFACE_REPARATION, COULEUR_MARQUAGES_SOL)
        pyxel.circ(LIMITE_OUEST_TERRAIN + DISTANCE_PT_PENALTY_CAGE, LARGEUR / 2, RAYON_CERCLE_SURFACE_REPARATION - EPAISSEUR_MARQUAGES_SOL, COULEUR_TERRAIN)
        pyxel.circ(LIMITE_EST_TERRAIN - DISTANCE_PT_PENALTY_CAGE, LARGEUR / 2, RAYON_CERCLE_SURFACE_REPARATION, COULEUR_MARQUAGES_SOL)
        pyxel.circ(LIMITE_EST_TERRAIN - DISTANCE_PT_PENALTY_CAGE, LARGEUR / 2, RAYON_CERCLE_SURFACE_REPARATION - EPAISSEUR_MARQUAGES_SOL, COULEUR_TERRAIN)
        
        # marquages sol
        pyxel.rect(LONGUEUR_BORD, LARGEUR_BORD, LONGUEUR - 2 * LONGUEUR_BORD, EPAISSEUR_MARQUAGES_SOL, COULEUR_MARQUAGES_SOL)
        pyxel.rect(LONGUEUR_BORD, LARGEUR_BORD, EPAISSEUR_MARQUAGES_SOL, LARGEUR - 2 * LARGEUR_BORD, COULEUR_MARQUAGES_SOL)
        pyxel.rect(LONGUEUR_BORD, LARGEUR - LARGEUR_BORD - EPAISSEUR_MARQUAGES_SOL, LONGUEUR - 2 * LONGUEUR_BORD, EPAISSEUR_MARQUAGES_SOL, COULEUR_MARQUAGES_SOL)
        pyxel.rect(LONGUEUR - LONGUEUR_BORD - EPAISSEUR_MARQUAGES_SOL, LARGEUR_BORD, EPAISSEUR_MARQUAGES_SOL, LARGEUR - 2 * LARGEUR_BORD, COULEUR_MARQUAGES_SOL)

        # cercle centre
        pyxel.circ(LONGUEUR / 2 - EPAISSEUR_MARQUAGES_SOL / 2, LARGEUR / 2, RAYON_CERLCE_CENTRE, COULEUR_MARQUAGES_SOL)
        pyxel.circ(LONGUEUR / 2 - EPAISSEUR_MARQUAGES_SOL / 2, LARGEUR / 2, RAYON_CERLCE_CENTRE - EPAISSEUR_MARQUAGES_SOL, COULEUR_TERRAIN)

        # trait centre
        pyxel.rect(LONGUEUR / 2 - EPAISSEUR_MARQUAGES_SOL / 2, LARGEUR_BORD, EPAISSEUR_MARQUAGES_SOL, LARGEUR - 2 * LARGEUR_BORD, COULEUR_MARQUAGES_SOL)

        # surface reparation
        pyxel.rect(LIMITE_OUEST_TERRAIN, LARGEUR / 2 - LARGEUR_SURFACE_REPARATION / 2, LONGUEUR_SURFACE_REPARATION, LARGEUR_SURFACE_REPARATION, COULEUR_MARQUAGES_SOL)
        pyxel.rect(LIMITE_OUEST_TERRAIN + EPAISSEUR_MARQUAGES_SOL, LARGEUR / 2 - LARGEUR_SURFACE_REPARATION / 2 + EPAISSEUR_MARQUAGES_SOL, LONGUEUR_SURFACE_REPARATION - 2 * EPAISSEUR_MARQUAGES_SOL, LARGEUR_SURFACE_REPARATION - 2 * EPAISSEUR_MARQUAGES_SOL, COULEUR_TERRAIN)
        pyxel.rect(LIMITE_EST_TERRAIN - LONGUEUR_SURFACE_REPARATION, LARGEUR / 2 - LARGEUR_SURFACE_REPARATION / 2, LONGUEUR_SURFACE_REPARATION, LARGEUR_SURFACE_REPARATION, COULEUR_MARQUAGES_SOL)
        pyxel.rect(LIMITE_EST_TERRAIN - LONGUEUR_SURFACE_REPARATION + EPAISSEUR_MARQUAGES_SOL, LARGEUR / 2 - LARGEUR_SURFACE_REPARATION / 2 + EPAISSEUR_MARQUAGES_SOL, LONGUEUR_SURFACE_REPARATION - 2 * EPAISSEUR_MARQUAGES_SOL, LARGEUR_SURFACE_REPARATION - 2 * EPAISSEUR_MARQUAGES_SOL, COULEUR_TERRAIN)

        # surface avant cage
        pyxel.rect(LIMITE_OUEST_TERRAIN, LARGEUR / 2 - LARGEUR_SURFACE_AVANT_CAGE / 2, LONGUEUR_SURFACE_AVANT_CAGE, LARGEUR_SURFACE_AVANT_CAGE, COULEUR_MARQUAGES_SOL)
        pyxel.rect(LIMITE_OUEST_TERRAIN + EPAISSEUR_MARQUAGES_SOL, LARGEUR / 2 - LARGEUR_SURFACE_AVANT_CAGE / 2 + EPAISSEUR_MARQUAGES_SOL, LONGUEUR_SURFACE_AVANT_CAGE - 2 * EPAISSEUR_MARQUAGES_SOL, LARGEUR_SURFACE_AVANT_CAGE - 2 * EPAISSEUR_MARQUAGES_SOL, COULEUR_TERRAIN)
        pyxel.rect(LIMITE_EST_TERRAIN - LONGUEUR_SURFACE_AVANT_CAGE, LARGEUR / 2 - LARGEUR_SURFACE_AVANT_CAGE / 2, LONGUEUR_SURFACE_AVANT_CAGE, LARGEUR_SURFACE_AVANT_CAGE, COULEUR_MARQUAGES_SOL)
        pyxel.rect(LIMITE_EST_TERRAIN - LONGUEUR_SURFACE_AVANT_CAGE + EPAISSEUR_MARQUAGES_SOL, LARGEUR / 2 - LARGEUR_SURFACE_AVANT_CAGE / 2 + EPAISSEUR_MARQUAGES_SOL, LONGUEUR_SURFACE_AVANT_CAGE - 2 * EPAISSEUR_MARQUAGES_SOL, LARGEUR_SURFACE_AVANT_CAGE - 2 * EPAISSEUR_MARQUAGES_SOL, COULEUR_TERRAIN)
        
        # pt penalty
        pyxel.circ(LIMITE_OUEST_TERRAIN + DISTANCE_PT_PENALTY_CAGE, LARGEUR / 2, RAYON_PT_PENALTY, COULEUR_MARQUAGES_SOL)
        pyxel.circ(LIMITE_EST_TERRAIN - DISTANCE_PT_PENALTY_CAGE, LARGEUR / 2, RAYON_PT_PENALTY, COULEUR_MARQUAGES_SOL)
